spring.application.name=RoboDelivery
spring.datasource.url=jdbc:h2:mem:robodelivery;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

minimum-loading-battery=25
minimum-box-weight-limit=0.01
maximum-box-weight-limit=500.00
successful-return-webhook-key= Robo-delivery-T5wre7252jTTUdst
